import bpy
from stored_views_advanced.shared.prop import PropsStore


class Properties(bpy.types.PropertyGroup, PropsStore):
    display_mode: bpy.props.StringProperty()
    filter_id_type: bpy.props.StringProperty()
    filter_invert: bpy.props.BoolProperty()
    filter_state: bpy.props.StringProperty()
    filter_text: bpy.props.StringProperty()
    show_mode_column: bpy.props.BoolProperty()
    show_region_header: bpy.props.BoolProperty()
    show_restrict_column_enable: bpy.props.BoolProperty()
    show_restrict_column_hide: bpy.props.BoolProperty()
    show_restrict_column_holdout: bpy.props.BoolProperty()
    show_restrict_column_indirect_only: bpy.props.BoolProperty()
    show_restrict_column_render: bpy.props.BoolProperty()
    show_restrict_column_select: bpy.props.BoolProperty()
    show_restrict_column_viewport: bpy.props.BoolProperty()
    use_filter_case_sensitive: bpy.props.BoolProperty()
    use_filter_children: bpy.props.BoolProperty()
    use_filter_collection: bpy.props.BoolProperty()
    use_filter_complete: bpy.props.BoolProperty()
    use_filter_id_type: bpy.props.BoolProperty()
    use_filter_lib_override: bpy.props.BoolProperty()
    use_filter_lib_override_system: bpy.props.BoolProperty()
    use_filter_object: bpy.props.BoolProperty()
    use_filter_object_armature: bpy.props.BoolProperty()
    use_filter_object_camera: bpy.props.BoolProperty()
    use_filter_object_content: bpy.props.BoolProperty()
    use_filter_object_empty: bpy.props.BoolProperty()
    use_filter_object_light: bpy.props.BoolProperty()
    use_filter_object_mesh: bpy.props.BoolProperty()
    use_filter_object_others: bpy.props.BoolProperty()
    use_filter_view_layers: bpy.props.BoolProperty()
    use_sort_alpha: bpy.props.BoolProperty()
    use_sync_select: bpy.props.BoolProperty()
