from bpy.types import PropertyGroup, Object, StudioLight
from bpy.props import (
    FloatProperty,
    FloatVectorProperty,
    StringProperty,
    EnumProperty,
    BoolProperty,
    BoolVectorProperty,
    IntProperty,
    PointerProperty,
)
from stored_views_advanced.shared.prop import PropsStore


class OverlayProperties(PropertyGroup, PropsStore):
    backwire_opacity: FloatProperty()
    display_handle: StringProperty()
    fade_inactive_alpha: FloatProperty()
    gpencil_fade_layer: FloatProperty()
    gpencil_fade_objects: FloatProperty()
    gpencil_grid_opacity: FloatProperty()
    gpencil_vertex_paint_opacity: FloatProperty()
    grid_lines: IntProperty()
    grid_scale: FloatProperty()
    grid_scale_unit: FloatProperty()
    grid_subdivisions: IntProperty()
    normals_constant_screen_size: FloatProperty()
    normals_length: FloatProperty()
    sculpt_mode_face_sets_opacity: FloatProperty()
    sculpt_mode_mask_opacity: FloatProperty()
    show_annotation: BoolProperty()
    show_axis_x: BoolProperty()
    show_axis_y: BoolProperty()
    show_axis_z: BoolProperty()
    show_bones: BoolProperty()
    show_cursor: BoolProperty()
    show_curve_normals: BoolProperty()
    show_edge_bevel_weight: BoolProperty()
    show_edge_crease: BoolProperty()
    show_edge_seams: BoolProperty()
    show_edge_sharp: BoolProperty()
    show_edges: BoolProperty()
    show_extra_edge_angle: BoolProperty()
    show_extra_edge_length: BoolProperty()
    show_extra_face_angle: BoolProperty()
    show_extra_face_area: BoolProperty()
    show_extra_indices: BoolProperty()
    show_extras: BoolProperty()
    show_face_center: BoolProperty()
    show_face_normals: BoolProperty()
    show_face_orientation: BoolProperty()
    show_faces: BoolProperty()
    show_fade_inactive: BoolProperty()
    show_floor: BoolProperty()
    show_freestyle_edge_marks: BoolProperty()
    show_freestyle_face_marks: BoolProperty()
    show_look_dev: BoolProperty()
    show_motion_paths: BoolProperty()
    show_object_origins: BoolProperty()
    show_object_origins_all: BoolProperty()
    show_occlude_wire: BoolProperty()
    show_onion_skins: BoolProperty()
    show_ortho_grid: BoolProperty()
    show_outline_selected: BoolProperty()
    show_overlays: BoolProperty()
    show_paint_wire: BoolProperty()
    show_relationship_lines: BoolProperty()
    show_split_normals: BoolProperty()
    show_stats: BoolProperty()
    show_statvis: BoolProperty()
    show_text: BoolProperty()
    show_vertex_normals: BoolProperty()
    show_weight: BoolProperty()
    show_wireframes: BoolProperty()
    show_wpaint_contours: BoolProperty()
    show_xray_bone: BoolProperty()
    texture_paint_mode_opacity: FloatProperty()
    use_gpencil_canvas_xray: BoolProperty()
    use_gpencil_fade_gp_objects: BoolProperty()
    use_gpencil_fade_layers: BoolProperty()
    use_gpencil_fade_objects: BoolProperty()
    use_gpencil_grid: BoolProperty()
    use_gpencil_multiedit_line_only: BoolProperty()
    use_gpencil_onion_skin: BoolProperty()
    use_gpencil_show_directions: BoolProperty()
    use_gpencil_show_material_name: BoolProperty()
    use_normals_constant_screen_size: BoolProperty()
    vertex_opacity: FloatProperty()
    vertex_paint_mode_opacity: FloatProperty()
    weight_paint_mode_opacity: FloatProperty()
    wireframe_opacity: FloatProperty()
    wireframe_threshold: FloatProperty()
    xray_alpha_bone: FloatProperty()


class ShadingProperties(PropertyGroup, PropsStore):
    aov_name: StringProperty()
    background_color: FloatVectorProperty()
    background_type: StringProperty()
    cavity_ridge_factor: FloatProperty()
    cavity_type: StringProperty()
    cavity_valley_factor: FloatProperty()
    color_type: StringProperty()
    curvature_ridge_factor: FloatProperty()
    curvature_valley_factor: FloatProperty()
    light: StringProperty()
    object_outline_color: FloatVectorProperty()
    render_pass: StringProperty()
    shadow_intensity: FloatProperty()
    show_backface_culling: BoolProperty()
    show_cavity: BoolProperty()
    show_object_outline: BoolProperty()
    show_shadows: BoolProperty()
    show_specular_highlight: BoolProperty()
    show_xray: BoolProperty()
    show_xray_wireframe: BoolProperty()
    single_color: FloatVectorProperty()
    studio_light: StringProperty()
    studiolight_background_alpha: FloatProperty()
    studiolight_background_blur: FloatProperty()
    studiolight_intensity: FloatProperty()
    studiolight_rotate_z: FloatProperty()
    type: StringProperty()
    use_dof: BoolProperty()
    use_scene_lights: BoolProperty()
    use_scene_lights_render: BoolProperty()
    use_scene_world: BoolProperty()
    use_scene_world_render: BoolProperty()
    use_studiolight_view_rotation: BoolProperty()
    use_world_space_lighting: BoolProperty()
    wireframe_color_type: StringProperty()
    xray_alpha: FloatProperty()
    xray_alpha_wireframe: FloatProperty()


class Region3DProperties(PropertyGroup, PropsStore):
    clip_planes: FloatVectorProperty(size=(6, 4))
    is_orthographic_side_view: BoolProperty()
    is_perspective: BoolProperty()
    lock_rotation: BoolProperty()
    perspective_matrix: FloatVectorProperty(size=(4, 4))
    show_sync_view: BoolProperty()
    use_box_clip: BoolProperty()
    use_clip_planes: BoolProperty()
    view_camera_offset: FloatVectorProperty(size=2)
    view_camera_zoom: FloatProperty()
    view_distance: FloatProperty()
    view_location: FloatVectorProperty()
    view_matrix: FloatVectorProperty(size=(4, 4))
    view_perspective: StringProperty()
    view_rotation: FloatVectorProperty(size=4)
    window_matrix: FloatVectorProperty(size=(4, 4))


class ViewProperties(PropertyGroup, PropsStore):
    camera: PointerProperty(type=Object)
    clip_start: FloatProperty()
    clip_end: FloatProperty()
    icon_from_show_object_viewport: IntProperty()
    lens: FloatProperty()
    lock_bone: StringProperty()
    lock_camera: BoolProperty()
    lock_cursor: BoolProperty()
    lock_object: PointerProperty(type=Object)
    mirror_xr_session: BoolProperty()
    overlay: PointerProperty(type=OverlayProperties)
    region_3d: PointerProperty(type=Region3DProperties)
    render_border_max_x: FloatProperty()
    render_border_max_y: FloatProperty()
    render_border_min_x: FloatProperty()
    render_border_min_y: FloatProperty()
    shading: PointerProperty(type=ShadingProperties)
    show_bundle_names: BoolProperty()
    show_camera_path: BoolProperty()
    show_gizmo: BoolProperty()
    show_gizmo_camera_dof_distance: BoolProperty()
    show_gizmo_camera_lens: BoolProperty()
    show_gizmo_context: BoolProperty()
    show_gizmo_empty_force_field: BoolProperty()
    show_gizmo_empty_image: BoolProperty()
    show_gizmo_light_look_at: BoolProperty()
    show_gizmo_light_size: BoolProperty()
    show_gizmo_navigate: BoolProperty()
    show_gizmo_object_rotate: BoolProperty()
    show_gizmo_object_scale: BoolProperty()
    show_gizmo_object_translate: BoolProperty()
    show_gizmo_tool: BoolProperty()
    show_object_select_armature: BoolProperty()
    show_object_select_camera: BoolProperty()
    show_object_select_curve: BoolProperty()
    show_object_select_empty: BoolProperty()
    show_object_select_font: BoolProperty()
    show_object_select_grease_pencil: BoolProperty()
    show_object_select_hair: BoolProperty()
    show_object_select_lattice: BoolProperty()
    show_object_select_light: BoolProperty()
    show_object_select_light_probe: BoolProperty()
    show_object_select_mesh: BoolProperty()
    show_object_select_meta: BoolProperty()
    show_object_select_pointcloud: BoolProperty()
    show_object_select_speaker: BoolProperty()
    show_object_select_surf: BoolProperty()
    show_object_select_volume: BoolProperty()
    show_object_viewport_armature: BoolProperty()
    show_object_viewport_camera: BoolProperty()
    show_object_viewport_curve: BoolProperty()
    show_object_viewport_empty: BoolProperty()
    show_object_viewport_font: BoolProperty()
    show_object_viewport_grease_pencil: BoolProperty()
    show_object_viewport_hair: BoolProperty()
    show_object_viewport_lattice: BoolProperty()
    show_object_viewport_light: BoolProperty()
    show_object_viewport_light_probe: BoolProperty()
    show_object_viewport_mesh: BoolProperty()
    show_object_viewport_meta: BoolProperty()
    show_object_viewport_pointcloud: BoolProperty()
    show_object_viewport_speaker: BoolProperty()
    show_object_viewport_surf: BoolProperty()
    show_object_viewport_volume: BoolProperty()
    show_reconstruction: BoolProperty()
    show_region_hud: BoolProperty()
    show_region_tool_header: BoolProperty()
    show_region_toolbar: BoolProperty()
    show_region_ui: BoolProperty()
    show_stereo_3d_cameras: BoolProperty()
    show_stereo_3d_convergence_plane: BoolProperty()
    show_stereo_3d_volume: BoolProperty()
    stereo_3d_camera: StringProperty()
    stereo_3d_convergence_plane_alpha: FloatProperty()
    stereo_3d_eye: StringProperty()
    stereo_3d_volume_alpha: FloatProperty()
    tracks_display_size: FloatProperty()
    tracks_display_type: StringProperty()
    use_local_camera: BoolProperty()
    use_local_collections: BoolProperty()
    use_render_border: BoolProperty()
